### ISSUE TITLE
Open other then .wordy document throws exception

### ISSUE THREAD

**Issue by Naoghuman** [VocabHunter/VocabHunter#14]
Hi Adam,

I downloaded the zip VocabHunter-1.0.15.

I see that 'Open' should used for loading a saved session. But I see that it's possible to choose the option `All Files (*.*)` in the FileChooser. So I give it a try :smile: .

I try to load a xy.log file, here the program throws an exception about the extention `unknown extention: .log` and loading a xy.properties throws the following exception (see the attached file).

I think if no other then a `.wordy` document can be open with the `Open` button then the FileChooser shouldn't have the option to choose `All Files (*.*)`.

Greetings
Peter

[exception.txt](https://github.com/VocabHunter/VocabHunter/files/312353/exception.txt)

**Comment by AdamCarroll** [comment]
Hi Peter,

You're absolutely right.  The system can only load `.wordy` files with the "Open" button so it doesn't make sense to show the "All Files" option.  I'll remove it to avoid confusion.

Thanks for the feedback!

Cheers, Adam.

**Comment by AdamCarroll** [comment]
This problem is fixed in 4de40c8552fd3a2665c83a76047537720a32af3c and will be included in the next release.

**Comment by AdamCarroll** [comment]
This fix is now live in the latest release.  Thanks again @Naoghuman !

The release notes are here: http://vocabhunter.github.io/2016/07/17/VocabHunter-v1.0.16-Released.html
