### ISSUE TITLE
Feature Request: Add Notes to Words

### ISSUE THREAD

**Issue by hal3firefly** [VocabHunter/VocabHunter#23]
Hi, 

I apologize if this is not the place to ask questions or make comments. I have never used github before and I have just opened an account. 

First, thank you so much for making this app. I am learning French at the moment and it is helping out so much.  I have no programming knowledge, yet. But I hope to learn to make something as I am learning Java.

Anyway, I wanted to make a feature request. Apologies if this is not the place, but I couldn't find an email to reach you at. I would like if the text I marked unknown and known had a small text box under it to make notes or add comments. I have added a screenshot to show what it would look like. Thank you.

![screenshot-app](https://user-images.githubusercontent.com/33811922/32994364-e4da94e2-cd2b-11e7-8255-a14671f54274.png)

**Comment by AdamCarroll** [comment]
Hi @hal3firefly 

Thanks for your suggestion.  I think that the idea of being able to add notes to a word sounds like useful addition to VocabHunter.  I’ll have a crack at implementing it but I can’t make any promises now about when it will be ready.

I’m glad you find VocabHunter useful.  It’s always good to hear from people who use the system.  And I hope you have an enjoyable and successful time studying French.

I’ve been thinking about how best to implement this.  It will help me to do this if I know a little bit more about how you use VocabHunter.  Do you tend to transfer your word list from VocabHunter to, for example, a flashcard program to study the new vocab or do you study it directly in VocabHunter?  Also do you think that you are likely to want to add notes to lots of words from a given book or just a handful?

Cheers, Adam.

**Comment by hal3firefly** [comment]
Hi,

Thanks for the quick reply. I do enjoy your program and find it really useful. And I happened to find it completely by accident. 

I think it would be nice if I could export word list of either "know" or "don't know" to an excel sheet or simple text file. I also use Anki to make flashcards and this feature would speed up my vocab learning. 

I think I would add more than less words to any given book. At least, I will add the gender of words (masculine or feminine) and a sample sentence to give me context with English equivalent. I use reverso or linguee to find sentences. 

But I'm not trying to put a paragraph of information on each word in VocabHunter. I just want to add some definitions or grammatical rules so that I don't have to switch back and forth with a dictionary when I read again for the second time.

I have a few more features I would like, but I don't want to pressure you. Your program is still new and not the most polished but it has helped me alot. And I have tried just about every program in the language learning world. 

Take your time, there's no rush in adding features. I appreciate you working on this software. Have a nice day.

**Comment by AdamCarroll** [comment]
OK, great.  That's useful to know.

By the way, did you know that you can export the words that you've marked as being new to you (the "don't know" words)?  You do it with the "Export Selection" button, as described [here](https://vocabhunter.github.io/help/#exporting-the-new-vocab).  The feature writes the words to a simple text file that you can then load into Excel or anything else that reads plain text.

**Comment by hal3firefly** [comment]
I found it now. Unfortunately, I skimmed the documentation the first time but the software was very easy to use. Thanks, this makes it easier.

**Comment by AdamCarroll** [comment]
You're welcome.  I hope you find it useful.

By the way, if you have friends or colleagues learning French as well, don't forget to share VocabHunter with them.

**Comment by AdamCarroll** [comment]
I've just released version 1.0.22 of VocabHunter that includes this feature.  Take a look at the [release notes](https://vocabhunter.github.io/2017/12/10/vocabhunter-v1.0.22-released.html) for more details.

**Comment by AdamCarroll** [comment]
I'll update the "how to guide" soon.  Here's a view of the feature in action.  I hope you find it useful.  Enjoy!
![vocabhunter-v1 0 22-add-word-note](https://user-images.githubusercontent.com/15148135/33807323-2fde85c0-ddd5-11e7-9a27-18b4213adc69.png)

**Comment by AdamCarroll** [comment]
I've added a section [here](https://vocabhunter.github.io/help/#adding-notes) in the "how to" documentation giving a short explanation of how to add a note to a word.

**Comment by hal3firefly** [comment]
Sorry for the late reply. I was swamped with exams and had nonstop studying. 
You are amazing. Thanks for taking the time to put a small request like mine in your program. Appreciate it and checking it out now. Will get back to you with any bugs or good reports. 

Thanks again.

**Comment by AdamCarroll** [comment]
You're welcome!

If you find any bugs anywhere in VocabHunter, please do create issues for them here in GitHub.  Here's a guide: [How to Report a Bug](https://vocabhunter.github.io/issues/).

And I hope the studying is going well.
