### ISSUE TITLE
Apache Tika Generates Warning Output

### ISSUE THREAD

**Issue by AdamCarroll** [VocabHunter/VocabHunter#24]
When reading documents, Apache tika generates warning output.  For example:
```
Dec 09, 2017 11:45:02 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: JBIG2ImageReader not loaded. jbig2 files will be ignored
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.
TIFFImageWriter not loaded. tiff files will not be processed
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.
J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

Dec 09, 2017 11:45:03 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
```
It should be possible to disable this as image reading etc. is not required for VocabHunter.

**Comment by AdamCarroll** [comment]
This two JIRA tickets seem to relevant to this: [TIKA-2389](https://issues.apache.org/jira/browse/TIKA-2389) and [TIKA-2490](https://issues.apache.org/jira/browse/TIKA-2490).

**Comment by wolfiesonfire** [comment]
https://github.com/apache/tika/blob/master/tika-parsers/src/main/java/org/apache/tika/parser/pdf/PDFParser.java

```
try {
    Class.forName("com.github.jaiimageio.jpeg2000.impl.J2KImageReader");
} catch (ClassNotFoundException e) {
    sb.append("J2KImageReader not loaded. JPEG2000 files will not be processed.\n");
    sb.append("See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io\n");
    sb.append("for optional dependencies.\n");
}
```

**Comment by AdamCarroll** [comment]
This is now fixed.  The first step was to redirect the JUL logging to SLF4J: 0f71fe603674d2668a53dcd4715c662517cbb88d

Then the Apache Tika log level can be raised to error: 58a72a1ae2a4cacfee701911b44da75b412b2396

**Comment by AdamCarroll** [comment]
This problem no longer exists with Apache Tika v2.1.0.  I've removed the workaround and the updated the Tika version: 4e1a27257485f4b1bd013d04e697493dd51914bd
