### ISSUE TITLE
Use javafx-gradle plugin

### ISSUE THREAD

**Issue by jperedadnr** [VocabHunter/VocabHunter#36]
In the `gui` project you could use the `javafx-gradle-plugin` (see [link](https://github.com/openjfx/javafx-gradle-plugin), or openjfx [gradle samples](https://github.com/openjfx/samples)) to simplify dealing with the JavaFX modules.

You could remove `javafxCompile`, and just use something like:

```
plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.7'
}

javafx {
    modules = ['javafx.controls', 'javafx.fxml']
}

run {
    jvmArgs += ['--add-exports', 'javafx.base/com.sun.javafx.runtime=ALL-UNNAMED']
}

```

**Comment by AdamCarroll** [comment]
Thanks @jperedadnr ! That looks very interesting. However, I'm not sure how it would work with the part of the build that I use for creating the self-contained installable bundles using the Java Packager.  To do this, I make a copy of all of the project jars, including the dependencies to go in the bundle.  But I explicitly exclude the JavaFX dependencies.  This is because the JavaFX modules are then passed in as JMOD files in the bundling process.  You can see the code that I use to copy the jars but exclude the JavaFX dependencies from the bundle here:

https://github.com/VocabHunter/VocabHunter/blob/e2d1e16fbc491f2af2e27c0c0fa143f1b52beda8/gui/build.gradle#L92-L96

Do you know if this is possible with the `javafx-gradle-plugin`?

**Comment by jperedadnr** [comment]
In fact, given that the JavaFX plugin uses `implementation` instead of `compile`, both `configurations.compile` and `configurations.runtime` won't include JavaFX at all (you can get them via `configurations.compileClasspath`/`configurations.runtimeClasspath`). 
In this case I believe you can remove directly `configurations.javafxCompile`.

Also, it is possible to use the JavaFX jars directly instead of the jmods, if you take the jars you get from Gradle, with the platform classifier, as those contain the native libraries. Imo this is a better aproach as it saves you from the need of a local download of the JavaFX jmods.

**Comment by AdamCarroll** [comment]
Thanks, that's very helpful. It sounds like it's well worth trying what you suggest. To follow this, I've created the pull request #37.

In the first commit, a8b4a8ee7007e860b288379cd76faa81ef940a54, I've replaced the explicit dependencies with the plugin as you suggest. It seems to work nicely.  It does make me wonder though if I should in fact be using the `implementation` configuration in my own dependencies and if I do whether I would then hit the problem of needing to exclude the JavaFX dependencies.  That said, the pull request code looks cleaner and simpler to maintain.

Your second suggestion of replacing the JMODS with the JavaFX jars is an interesting one.  I had a crack at this by removing the modules from the Java Packager command line and relying on the jars.  However, this gave me the following error:
~~~
Error: JavaFX runtime components are missing, and are required to run this application
~~~
So my guess is not I'm interpreting your suggestion correctly.

**Comment by jperedadnr** [comment]
Your PR looks good, those are the expected changes for the gui build.

`compile` is deprecated, so you should move to `implementation`, indeed.

If you want to bundle your dependencies excluding the JavaFX ones, there are a few options. For instance, the shadow plugin, allows excluding them, like we do for Scene Builder [here](https://github.com/gluonhq/scenebuilder/blob/master/app/build.gradle#L21).

You can replace jmods with the jars that are in .m2, those including the platform classifier, as they include the native libraries. So one way to do it is to copy them from .m2 to a libs folder in your project, and them adding that library to the module-path option of the jpackage tool.

Since these are the artifacts that are on the runtime classpath, you can do something like I do in this [SO answer](https://stackoverflow.com/questions/54063041/package-a-non-modular-javafx-application/54065502#54065502):

```
task copyDependencies(type: Copy) {
    dependsOn 'build'
    from configurations.runtimeClasspath
    into "${buildDir}/libs"
}

commandLine "${java_home}/bin/jpackage", 'create-installer', "dmg",
            '--output', "${installer}", "--name", "${appName}",
            '--verbose', '--echo-mode', '--module-path', 'build/libs',...
```

**Comment by AdamCarroll** [comment]
Great.  Thanks for taking the time to help and gather this information.  I've been playing around with this and based on my understanding of your suggestion and some experimentation, I've come up with this: a5d30fa82d6974c9e025c25c8252e6cfec27c1f9.

I've done a quick test on the Mac (but not yet on Linux and Windows) and it seems to work.  Is that what you had in mind?  Are there any differences in the JMODs and Jars that come from Maven Central like this?  I can see a slight size difference.

Running the new `copyJavafxModules` modules seems to work nicely:
~~~
$ ./gradlew clean :gui:copyJavafxModules

BUILD SUCCESSFUL in 0s
6 actionable tasks: 2 executed, 4 up-to-date

$ ls -lh gui/build/javafx-modules
total 7.9M
-rw-r--r-- 1 adam staff 733K Feb  6 22:41 javafx-base-11.0.2-mac.jar
-rw-r--r-- 1 adam staff 2.4M Feb  6 22:41 javafx-controls-11.0.2-mac.jar
-rw-r--r-- 1 adam staff 125K Feb  6 22:41 javafx-fxml-11.0.2-mac.jar
-rw-r--r-- 1 adam staff 4.6M Feb  6 22:41 javafx-graphics-11.0.2-mac.jar
~~~

However, I wonder if there's a cleaner way to define this using the the `javafx-gradle-plugin` rather than the way I've done it in the Gradle script.

**Comment by jperedadnr** [comment]
I see that you had the `package` project based on two inputs: JavaFX jmods (for --module-path), and runtime dependencies (without JavaFX, for --input). 

Now you have replaced the jmods with the jars from `configuration.javafxModules`, which is good because you don't need jmods anymore, all comes from Gradle.
 
However, this means that you have to track the JavaFX jars from dependencies.
But you could just do something like:

```
task copyJavafxModules(type: Copy) {
        dependsOn 'build'
        from configurations.runtimeClasspath
        include "javafx*${javafx.platform.classifier}.jar"
        into "${buildDir}/javafx-modules"
    }
```
That should do it as well, and you won't need to define `configuration.javafxModules`.

About jmods and jars, the former has also config files.

**Comment by jperedadnr** [comment]
Actually, if you think about it, you can create a task to do all this automatically.

For instance, something like this works for me (based on current build 8 of the [jpackage](http://jdk.java.net/jpackage/)):

```
mainClassName = "your.mainclass"

def java_home = '/path/to/Downloads/jdk-13.jdk/Contents/Home'
def installer = 'build/installer'
def appName = "${rootProject.name}"

// extract and copy non-modular dependencies, including the app's jar:
task copyDependencies(type: Copy) {
    from "${buildDir}/libs/"
    from configurations.runtimeClasspath.resolvedConfiguration.resolvedArtifacts.findAll {
        zipTree(it.file).matching { include "/module-info.class" }.size() == 0
    }.collect { it.file }
    into "${buildDir}/tmp/non-mod"
}

// Extract and copy modular dependencies:
task copyModDependencies(type: Copy) {
    from configurations.runtimeClasspath.resolvedConfiguration.resolvedArtifacts.findAll {
        zipTree(it.file).matching { include "/module-info.class" }.size() != 0
    }.collect { it.file }
    into "${buildDir}/tmp/mod"
}

task jpackage(type: Exec) {
    dependsOn build
    dependsOn 'copyDependencies'
    dependsOn 'copyModDependencies'

    if (java_home == null) {
        throw new RuntimeException("java_home is not defined.")
    }

    commandLine "${java_home}/bin/jpackage", 'create-installer', "dmg",
            '--output', "${installer}", "--name", "${appName}",
            '--verbose', '--module-path', "${buildDir}/tmp/mod",
            '--add-modules', "${javafx.modules.join(",")}",
            '--input', "${buildDir}/tmp/non-mod",
            '--class', "${mainClassName}", '--main-jar', "${appName}.jar"
}
```

Running `./gradlew clean jpackage` creates successfully the installer.

What do you think?

**Comment by AdamCarroll** [comment]
> I see that you had the `package` project based on two inputs: JavaFX jmods (for --module-path), and runtime dependencies (without JavaFX, for --input).
> 
> Now you have replaced the jmods with the jars from `configuration.javafxModules`, which is good because you don't need jmods anymore, all comes from Gradle.
> 
> However, this means that you have to track the JavaFX jars from dependencies.
> But you could just do something like:
> 
> ```
> task copyJavafxModules(type: Copy) {
>         dependsOn 'build'
>         from configurations.runtimeClasspath
>         include "javafx*${javafx.platform.classifier}.jar"
>         into "${buildDir}/javafx-modules"
>     }
> ```
> 
> That should do it as well, and you won't need to define `configuration.javafxModules`.
> 

This is a great simplification! Good idea.  Here's my version: 20e18891897db1f08d43ac65cb62f07fa8a33c19.

As you can see, I removed the `dependsOn 'build'` as this doesn't seem to be required if you test without it and run `./gradlew clean copyJavafxModules`.

> About jmods and jars, the former has also config files.

I'm intrigued about those config files.  Are they anything that might make JLink run an optimisation that we would miss out on like this?

**Comment by AdamCarroll** [comment]
> mainClassName = "your.mainclass"
> 
> def java_home = '/path/to/Downloads/jdk-13.jdk/Contents/Home'
> def installer = 'build/installer'
> def appName = "${rootProject.name}"
> 
> // extract and copy non-modular dependencies, including the app's jar:
> task copyDependencies(type: Copy) {
>  -----SNIP--
> Running `./gradlew clean jpackage` creates successfully the installer.
> 
> What do you think?

That looks interesting but it seems to lose some of the simplicity of your previous suggestion.  It looks like something generic that could be handled by a Gradle plugin though.  Also, I wonder if this would work in the case of a project with "real" modules (containing `module-info.class`) that refer to automatic modules.  I might be wrong but I think that JLink would object under those circumstances.  What do you think?

> def java_home = '/path/to/Downloads/jdk-13.jdk/Contents/Home'

You're way ahead of me.  I'm just joining the JDK 11 party. 😃

**Comment by jperedadnr** [comment]
About the jpackage tool: the one you are using was kind of a back port done in September with the very early stage of the jpackage project. The version available [here](
http://jdk.java.net/jpackage/) is from January, and since they moved the target to Java 13, they are using a sandboxed version of the current JDK 13-ea, probably very similar to the latest JDK 12-ea.

You can use this jpackage tool, and it would bundle that JDK 13, but you can still use JavaFX 11.0.2 on it. Of course you can still rely on the first version, as long as it serves your purposes. Either way, it is advised that neither of them should be used in production yet!

About the more complex approach I'm proposing, indeed that is for a plugin, but so far plugins like [this](https://github.com/beryx/badass-jlink-plugin) perform internal manipulations of the dependencies to allow `jlink` work. Otherwise it doesn't work when you refer automatic modules. Same happens with `jpackage`: you have only "pure" modules or you better use the mixed approach module path and classpath as you are already doing. 

I'm just proposing a more general way of dealing with any number of modular dependencies (not only JavaFX) and non-modular ones.

**Comment by AdamCarroll** [comment]
It's good to hear that work is progressing on the Java Packager. I think this is a key piece of software for a lot of us working with JavaFX. You mention that the new version will work with JavaFX 11.0.2.  Do you know if it will work with JDK 11 as well?  I'm guessing that a lot of people will be focussed on the LTS versions of Java from now onwards.

I like your more general approach to handling the modules and jars.  I think it will be something to look at in the future, especially if it becomes available in a plugin.  For now, I'm inclined to go with your original suggestion as it has the great benefit of simplicity whilst still making it possible to replace the JMODs with components from Maven Central.  I think that when this pull request is complete, VocabHunter will be a better project, thanks to your help.

**Comment by jperedadnr** [comment]
In theory you could create an installer for a custom image. So if you create a custom image with JDK 11, you will just use the jpackage tool bundle with JDK 13 to create that installer. I've did try it, but with no luck (probably not ready yet). But definitely it runs fine on Java 13 + JavaFX 11 (you can try that too).

Yes, for your project it makes sense the more simple approach, and it will be really useful for many people that take your project as a valuable reference.

**Comment by AdamCarroll** [comment]
I do hope that people find VocabHunter useful for reference. It shows the fun we Java programmers can have with JavaFX!

**Comment by AdamCarroll** [comment]
The build script and build instructions are now simplified following these changes: 870b647fd4d3c6fb3a3e3b190ff75de487d50ffe

**Comment by AdamCarroll** [comment]
The changes are now incorporated into the master branch.  Thanks for your suggestions, help and insight with this @jperedadnr . I'll have to buy you a beer if you're in Barcelona some time!

**Comment by jperedadnr** [comment]
What about next [Friday](https://www.meetup.com/es-ES/BarcelonaJUG/events/258506532/)?

**Comment by AdamCarroll** [comment]
Sounds good.  See you there!
