### ISSUE TITLE
Allow the user to copy the current word to the clipboard

### ISSUE THREAD

**Issue by yehia2amer** [VocabHunter/VocabHunter#42]
Add a menu item in the “Words” menu to allow the user to copy a word to the system clipboard. There should also be a keyboard shortcut, Control-C (or Command-C on the Mac) to perform the same action. The option should only be available when a session is open.

As Discussed with @AdamCarroll in #41

**Comment by AdamCarroll** [comment]
I've implemented this feature and it will be included in the next release of VocabHunter.

You can see the commit here: 3da23a5c1ee67938ae4ec3cb09cfe82bd14e8576

**Comment by AdamCarroll** [comment]
I've just released [VocabHunter v2.2.0](https://vocabhunter.github.io/2020/02/09/vocabhunter-v2.2.0-released.html) containing this feature.
