### ISSUE TITLE
building project with java 14

### ISSUE THREAD

**Issue by hosseinmp76** [VocabHunter/VocabHunter#48]
I downloaded the project and ran the createBundle task with java 14 successfully but it makes no jar.
I can run the project using gradle run with no problem.
java 14 has the jpackage tool officially but it has got some changes. for example the name has been changed from jpackager to jpackage so I had to change name in build.gradle and pass the -DJpackagerPath.

**Comment by AdamCarroll** [comment]
There is no support for JDK 14.  The project is currently based on JDK 11.  I've just started work to get everything working for JDK 16, now that the new `jpackage`  tool is "production-ready".  You can follow the progress in [this milestone](https://github.com/VocabHunter/VocabHunter/milestone/2).
