### ISSUE TITLE
There is no installation bundle for Windows

### ISSUE THREAD

**Issue by AdamCarroll** [VocabHunter/VocabHunter#5]
There are now installation bundles for Mac and Linux (`.dmg` and `.deb` files respectively) but there is nothing other than the `.zip` file for Windows.  The packaging should be updated to support the generation of `.exe` installers for Windows.

**Comment by AdamCarroll** [comment]
There is now an experimental installable Windows bundle.

**Comment by FibreFoX** [comment]
@AdamCarroll you might want to close this ;) I can clearly see `.exe-installers` on the [releases-page](https://github.com/VocabHunter/VocabHunter/releases)

**Comment by AdamCarroll** [comment]
@FibreFoX Unfortunately I can't quite close it yet.  I have that unfortunate "works on my machine" situation with the Windows installer.  On my Windows (virtual) machine it installs without a problem but a couple of people I know have reported a problem with the installer.  For that reason I've marked it as "experimental" and am directing Windows users to run it from the zip bundle (through the batch file).

After all of your help and insight into the Linux installer problem I'm left wondering if this might be something similar.  Perhaps there is something looking for an environment variable that for some reason isn't available on some versions of Windows.  This is all speculation though and without being able to reproduce the problem myself I can't get much further with the isssue yet.

**Comment by FibreFoX** [comment]
Just one note about the windows-installer: please make it able to choose the installation-target. Personally I hate having installers where this is not possible, I want to know where the application ends up on my drive ;)

This is possible by setting some additional argument for the bundler ([but requires more uptodate JDK, at least JDK1.8.0_60](http://stackoverflow.com/a/36933061/1961102)):
```groovy
jfx{
    // ...
    bundleArguments = [
        // ...
        // EXE-bundler has the option to enable choosing
        // the installation-directory as customer like other drive or foldername
        'installdirChooser': true
    ]
}
```

**Comment by FibreFoX** [comment]
Regarding the "works on my system": I have downloaded and installed your application, with the result: "works for me".

The Linux native launcher works a bit different in terms of finding the system JRE: https://github.com/teamfx/openjfx-8u-dev-rt/blob/06c64a2945127c281276ab9164afb723209bb908/modules/fxpackager/src/main/native/library/common/Package.cpp#L116

That DLL-file `packager.dll` is responsible to load the JRE whether it's bundled or not. On Linux, it checks for JRE_HOME (as we fixed this within the deb-installer), on Windows-systems it looks into the registry at some "known location", here some excerpt from the sourcecode:
```
// try to find current Java Home from registry
// HKLM\Software\JavaSoft\Java Runtime Environment\CurrentVersion
// HKLM\Software\JavaSoft\Java Runtime Environment\[CurrentVersion]\JavaHome
// return TRUE if found, and path is set in lpszJavaHome
// return FALSE otherwise
```

It might be worth to ask your people what their installed JDK/JRE is and what these registry values are containing.

**Comment by AdamCarroll** [comment]
@FibreFoX Great tip about `installdirChooser`.  I've tested it out - it works perfectly.  I've committed the change.  Thanks for that!

**Comment by AdamCarroll** [comment]
@FibreFoX When I get a chance I'll ask to check the registry of one of the machines that the installer fails on to see if I can get any pointers to the problem. Unfortunately, it might be a while before I get that chance though...

**Comment by AdamCarroll** [comment]
This problem is now fixed since the move to JDK 11.  The details of how this is achieved are in the article I wrote, [Using the Java Packager with JDK 11](https://medium.com/@adam_carroll/java-packager-with-jdk11-31b3d620f4a8).
